INSERT INTO `Categoria` (`nombre`, `descripcion`) VALUES ('java', 'libros de java')
INSERT INTO `Categoria` (`nombre`, `descripcion`) VALUES ('web', 'libros web')
INSERT INTO `Categoria` (`nombre`, `descripcion`) VALUES ('programacion', 'programacion')
INSERT INTO `Libros` (`isbn`, `titulo`, `autor`,  `precio`,`categoria`) VALUES ('1AB', 'Java', 'cecilio', 10, 'java')
INSERT INTO `Libros` (`isbn`, `titulo`, `autor`,  `precio`,`categoria`) VALUES ('2AC', 'Java Web', 'cecilio', 15, 'java')
INSERT INTO `Libros` (`isbn`, `titulo`, `autor`,  `precio`,`categoria`) VALUES ('3BC', 'html', 'gema', 8, 'web')
INSERT INTO `Libros` (`isbn`, `titulo`, `autor`,  `precio`,`categoria`) VALUES ('4BD', 'html5', 'andres', 20, 'web')
INSERT INTO `Libros` (`isbn`, `titulo`, `autor`,  `precio`,`categoria`) VALUES ('5EF', 'python', 'andres', 20, 'programacion')
INSERT INTO `Libros` (`isbn`, `titulo`, `autor`,  `precio`,`categoria`) VALUES ('6EF', 'jpa', 'cecilio', 20, 'java')